# Pandas Series

In [4]:
import pandas as pd
#pd as alias by using the as keyword
a=[1,3,5,6]
b=pd.Series(a,index=["a","b","c","d"])
print(b)

a    1
b    3
c    5
d    6
dtype: int64

In [6]:
#Accesing the data by using indexes
print(b["b"])

3

In [148]:
#Pandas as dictionaries
import pandas as pd
date={
    "calories":400,"date":300
}
b=pd.Series(date)
print(b)

calories    400
date        300
dtype: int64

In [149]:
b.index

Index(['calories', 'date'], dtype='object')

In [150]:
b.array

<PandasArray>
[400, 300]
Length: 2, dtype: int64

In [152]:
b.dtype

dtype('int64')

In [153]:
b.shape

(2,)

In [154]:
b.ndim

1

In [155]:
b.nbytes

16

In [156]:
b.memory_usage()

112

In [157]:
b.size

2

In [159]:
b.date

300

In [160]:
b.calories

400

# Pandas DataFrames

In [10]:
import pandas as pd
data={
    "calories":[40,30,20],
    "energy":[55,33,55]
}
b=pd.DataFrame(data)
print(b)

   calories  energy
0        40      55
1        30      33
2        20      55

In [14]:
#loc is used to access the rows of the dataset
# [] is used to print in Dataframe
# without[] the result in series
print(b.loc[0])
print(b.loc[[0]])

calories    40
energy      55
Name: 0, dtype: int64
   calories  energy
0        40      55

# Named the indexes and Accesing

In [15]:
import pandas as pd
data={
    "calories":[40,30,20],
    "energy":[55,33,55]
}
b=pd.DataFrame(data,index=["day 1","day 2","day 3"])
print(b)

       calories  energy
day 1        40      55
day 2        30      33
day 3        20      55

In [16]:
df=b.loc[["day 1"]]
print(df)

       calories  energy
day 1        40      55

# Loading the Files

In [21]:
import pandas as pd
df=pd.read_csv("heart.csv")
print(df)

     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0
1     37    1   2     130   250    0        1       187     0      3.5    0
2     41    0   1     130   204    0        0       172     0      1.4    2
3     56    1   1     120   236    0        1       178     0      0.8    2
4     57    0   0     120   354    0        1       163     1      0.6    2
5     57    1   0     140   192    0        1       148     0      0.4    1
6     56    0   1     140   294    0        0       153     0      1.3    1
7     44    1   1     120   263    0        1       173     0      0.0    2
8     52    1   2     172   199    1        1       162     0      0.5    2
9     57    1   2     150   168    0        1       174     0      1.6    2
10    54    1   0     140   239    0        1       160     0      1.2    2
11    48    0   2     130   275    0        1       139     0      0.2    2
12    49    1   1     130   266    0        1       171     0      0.6    2
13    64    1   3     110   211    0        0       144     1      1.8    1
14    58    0   3     150   283    1        0       162     0      1.0    2
15    50    0   2     120   219    0        1       158     0      1.6    1
16    58    0   2     120   340    0        1       172     0      0.0    2
17    66    0   3     150   226    0        1       114     0      2.6    0
18    43    1   0     150   247    0        1       171     0      1.5    2
19    69    0   3     140   239    0        1       151     0      1.8    2
20    59    1   0     135   234    0        1       161     0      0.5    1
21    44    1   2     130   233    0        1       179     1      0.4    2
22    42    1   0     140   226    0        1       178     0      0.0    2
23    61    1   2     150   243    1        1       137     1      1.0    1
24    40    1   3     140   199    0        1       178     1      1.4    2
25    71    0   1     160   302    0        1       162     0      0.4    2
26    59    1   2     150   212    1        1       157     0      1.6    2
27    51    1   2     110   175    0        1       123     0      0.6    2
28    65    0   2     140   417    1        0       157     0      0.8    2
29    53    1   2     130   197    1        0       152     0      1.2    0
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...
273   58    1   0     100   234    0        1       156     0      0.1    2
274   47    1   0     110   275    0        0       118     1      1.0    1
275   52    1   0     125   212    0        1       168     0      1.0    2
276   58    1   0     146   218    0        1       105     0      2.0    1
277   57    1   1     124   261    0        1       141     0      0.3    2
278   58    0   1     136   319    1        0       152     0      0.0    2
279   61    1   0     138   166    0        0       125     1      3.6    1
280   42    1   0     136   315    0        1       125     1      1.8    1
281   52    1   0     128   204    1        1       156     1      1.0    1
282   59    1   2     126   218    1        1       134     0      2.2    1
283   40    1   0     152   223    0        1       181     0      0.0    2
284   61    1   0     140   207    0        0       138     1      1.9    2
285   46    1   0     140   311    0        1       120     1      1.8    1
286   59    1   3     134   204    0        1       162     0      0.8    2
287   57    1   1     154   232    0        0       164     0      0.0    2
288   57    1   0     110   335    0        1       143     1      3.0    1
289   55    0   0     128   205    0        2       130     1      2.0    1
290   61    1   0     148   203    0        1       161     0      0.0    2
291   58    1   0     114   318    0        2       140     0      4.4    0
292   58    0   0     170   225    1        0       146     1      2.8    1
293   67    1   2     152   212    0        0       150     0      0.8    1
294   44    1   0     120   169    0        1       144     1      2.8    0
295   63    1   0     140   187    0        0       144     1      4.0    2
296   63    0   0     124   197    0        1       136     1      0.0    1
297   59    1   0     164   176    1        0        90     0      1.0    1
298   57    0   0     140   241    0        1       123     1      0.2    1
299   45    1   3     110   264    0        1       132     0      1.2    1
300   68    1   0     144   193    1        1       141     0      3.4    1
301   57    1   0     130   131    0        1       115     1      1.2    1
302   57    0   1     130   236    0        0       174     0      0.0    1

     caa  thall  output
0      0      1       1
1      0      2       1
2      0      2       1
3      0      2       1
4      0      2       1
5      0      1       1
6      0      2       1
7      0      3       1
8      0      3       1
9      0      2       1
10     0      2       1
11     0      2       1
12     0      2       1
13     0      2       1
14     0      2       1
15     0      2       1
16     0      2       1
17     0      2       1
18     0      2       1
19     2      2       1
20     0      3       1
21     0      2       1
22     0      2       1
23     0      2       1
24     0      3       1
25     2      2       1
26     0      2       1
27     0      2       1
28     1      2       1
29     0      2       1
..   ...    ...     ...
273    1      3       0
274    1      2       0
275    2      3       0
276    1      3       0
277    0      3       0
278    2      2       0
279    1      2       0
280    0      1       0
281    0      0       0
282    1      1       0
283    0      3       0
284    1      3       0
285    2      3       0
286    2      2       0
287    1      2       0
288    1      3       0
289    1      3       0
290    1      3       0
291    3      1       0
292    2      1       0
293    0      3       0
294    0      1       0
295    2      3       0
296    0      2       0
297    2      1       0
298    0      3       0
299    0      3       0
300    2      3       0
301    1      3       0
302    1      2       0

[303 rows x 14 columns]

In [23]:
# to__ string() is the method to print entire dataset
print(df.to_string())

     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  caa  thall  output
0     63    1   3     145   233    1        0       150     0      2.3    0    0      1       1
1     37    1   2     130   250    0        1       187     0      3.5    0    0      2       1
2     41    0   1     130   204    0        0       172     0      1.4    2    0      2       1
3     56    1   1     120   236    0        1       178     0      0.8    2    0      2       1
4     57    0   0     120   354    0        1       163     1      0.6    2    0      2       1
5     57    1   0     140   192    0        1       148     0      0.4    1    0      1       1
6     56    0   1     140   294    0        0       153     0      1.3    1    0      2       1
7     44    1   1     120   263    0        1       173     0      0.0    2    0      3       1
8     52    1   2     172   199    1        1       162     0      0.5    2    0      3       1
9     57    1   2     150   168    0        1       174     0      1.6    2    0      2       1
10    54    1   0     140   239    0        1       160     0      1.2    2    0      2       1
11    48    0   2     130   275    0        1       139     0      0.2    2    0      2       1
12    49    1   1     130   266    0        1       171     0      0.6    2    0      2       1
13    64    1   3     110   211    0        0       144     1      1.8    1    0      2       1
14    58    0   3     150   283    1        0       162     0      1.0    2    0      2       1
15    50    0   2     120   219    0        1       158     0      1.6    1    0      2       1
16    58    0   2     120   340    0        1       172     0      0.0    2    0      2       1
17    66    0   3     150   226    0        1       114     0      2.6    0    0      2       1
18    43    1   0     150   247    0        1       171     0      1.5    2    0      2       1
19    69    0   3     140   239    0        1       151     0      1.8    2    2      2       1
20    59    1   0     135   234    0        1       161     0      0.5    1    0      3       1
21    44    1   2     130   233    0        1       179     1      0.4    2    0      2       1
22    42    1   0     140   226    0        1       178     0      0.0    2    0      2       1
23    61    1   2     150   243    1        1       137     1      1.0    1    0      2       1
24    40    1   3     140   199    0        1       178     1      1.4    2    0      3       1
25    71    0   1     160   302    0        1       162     0      0.4    2    2      2       1
26    59    1   2     150   212    1        1       157     0      1.6    2    0      2       1
27    51    1   2     110   175    0        1       123     0      0.6    2    0      2       1
28    65    0   2     140   417    1        0       157     0      0.8    2    1      2       1
29    53    1   2     130   197    1        0       152     0      1.2    0    0      2       1
30    41    0   1     105   198    0        1       168     0      0.0    2    1      2       1
31    65    1   0     120   177    0        1       140     0      0.4    2    0      3       1
32    44    1   1     130   219    0        0       188     0      0.0    2    0      2       1
33    54    1   2     125   273    0        0       152     0      0.5    0    1      2       1
34    51    1   3     125   213    0        0       125     1      1.4    2    1      2       1
35    46    0   2     142   177    0        0       160     1      1.4    0    0      2       1
36    54    0   2     135   304    1        1       170     0      0.0    2    0      2       1
37    54    1   2     150   232    0        0       165     0      1.6    2    0      3       1
38    65    0   2     155   269    0        1       148     0      0.8    2    0      2       1
39    65    0   2     160   360    0        0       151     0      0.8    2    0      2       1
40    51    0   2     140   308    0        0       142     0      1.5    2    1      2       1
41    48    1   1     130   245    0        0       180     0      0.2    1    0      2       1
42    45    1   0     104   208    0        0       148     1      3.0    1    0      2       1
43    53    0   0     130   264    0        0       143     0      0.4    1    0      2       1
44    39    1   2     140   321    0        0       182     0      0.0    2    0      2       1
45    52    1   1     120   325    0        1       172     0      0.2    2    0      2       1
46    44    1   2     140   235    0        0       180     0      0.0    2    0      2       1
47    47    1   2     138   257    0        0       156     0      0.0    2    0      2       1
48    53    0   2     128   216    0        0       115     0      0.0    2    0      0       1
49    53    0   0     138   234    0        0       160     0      0.0    2    0      2       1
50    51    0   2     130   256    0        0       149     0      0.5    2    0      2       1
51    66    1   0     120   302    0        0       151     0      0.4    1    0      2       1
52    62    1   2     130   231    0        1       146     0      1.8    1    3      3       1
53    44    0   2     108   141    0        1       175     0      0.6    1    0      2       1
54    63    0   2     135   252    0        0       172     0      0.0    2    0      2       1
55    52    1   1     134   201    0        1       158     0      0.8    2    1      2       1
56    48    1   0     122   222    0        0       186     0      0.0    2    0      2       1
57    45    1   0     115   260    0        0       185     0      0.0    2    0      2       1
58    34    1   3     118   182    0        0       174     0      0.0    2    0      2       1
59    57    0   0     128   303    0        0       159     0      0.0    2    1      2       1
60    71    0   2     110   265    1        0       130     0      0.0    2    1      2       1
61    54    1   1     108   309    0        1       156     0      0.0    2    0      3       1
62    52    1   3     118   186    0        0       190     0      0.0    1    0      1       1
63    41    1   1     135   203    0        1       132     0      0.0    1    0      1       1
64    58    1   2     140   211    1        0       165     0      0.0    2    0      2       1
65    35    0   0     138   183    0        1       182     0      1.4    2    0      2       1
66    51    1   2     100   222    0        1       143     1      1.2    1    0      2       1
67    45    0   1     130   234    0        0       175     0      0.6    1    0      2       1
68    44    1   1     120   220    0        1       170     0      0.0    2    0      2       1
69    62    0   0     124   209    0        1       163     0      0.0    2    0      2       1
70    54    1   2     120   258    0        0       147     0      0.4    1    0      3       1
71    51    1   2      94   227    0        1       154     1      0.0    2    1      3       1
72    29    1   1     130   204    0        0       202     0      0.0    2    0      2       1
73    51    1   0     140   261    0        0       186     1      0.0    2    0      2       1
74    43    0   2     122   213    0        1       165     0      0.2    1    0      2       1
75    55    0   1     135   250    0        0       161     0      1.4    1    0      2       1
76    51    1   2     125   245    1        0       166     0      2.4    1    0      2       1
77    59    1   1     140   221    0        1       164     1      0.0    2    0      2       1
78    52    1   1     128   205    1        1       184     0      0.0    2    0      2       1
79    58    1   2     105   240    0        0       154     1      0.6    1    0      3       1
80    41    1   2     112   250    0        1       179     0      0.0    2    0      2       1
81    45    1   1     128   308    0        0       170     0      0.0    2    0      2       1
82    60    0   2     102   318    0        1       160     0      0.0    2    1      2       1
83    52    1   3     152   298    1        1       178     0      1.2    1    0      3       1
84    42    0   0     102   265    0        0       122     0      0.6    1    0      2       1
85    67    0   2     115   564    0        0       160     0      1.6    1    0      3       1
86    68    1   2     118   277    0        1       151     0      1.0    2    1      3       1
87    46    1   1     101   197    1        1       156     0      0.0    2    0      3       1
88    54    0   2     110   214    0        1       158     0      1.6    1    0      2       1
89    58    0   0     100   248    0        0       122     0      1.0    1    0      2       1
90    48    1   2     124   255    1        1       175     0      0.0    2    2      2       1
91    57    1   0     132   207    0        1       168     1      0.0    2    0      3       1
92    52    1   2     138   223    0        1       169     0      0.0    2    4      2       1
93    54    0   1     132   288    1        0       159     1      0.0    2    1      2       1
94    45    0   1     112   160    0        1       138     0      0.0    1    0      2       1
95    53    1   0     142   226    0        0       111     1      0.0    2    0      3       1
96    62    0   0     140   394    0        0       157     0      1.2    1    0      2       1
97    52    1   0     108   233    1        1       147     0      0.1    2    3      3       1
98    43    1   2     130   315    0        1       162     0      1.9    2    1      2       1
99    53    1   2     130   246    1        0       173     0      0.0    2    3      2       1
100   42    1   3     148   244    0        0       178     0      0.8    2    2      2       1
101   59    1   3     178   270    0        0       145     0      4.2    0    0      3       1
102   63    0   1     140   195    0        1       179     0      0.0    2    2      2       1
103   42    1   2     120   240    1        1       194     0      0.8    0    0      3       1
104   50    1   2     129   196    0        1       163     0      0.0    2    0      2       1
105   68    0   2     120   211    0        0       115     0      1.5    1    0      2       1
106   69    1   3     160   234    1        0       131     0      0.1    1    1      2       1
107   45    0   0     138   236    0        0       152     1      0.2    1    0      2       1
108   50    0   1     120   244    0        1       162     0      1.1    2    0      2       1
109   50    0   0     110   254    0        0       159     0      0.0    2    0      2       1
110   64    0   0     180   325    0        1       154     1      0.0    2    0      2       1
111   57    1   2     150   126    1        1       173     0      0.2    2    1      3       1
112   64    0   2     140   313    0        1       133     0      0.2    2    0      3       1
113   43    1   0     110   211    0        1       161     0      0.0    2    0      3       1
114   55    1   1     130   262    0        1       155     0      0.0    2    0      2       1
115   37    0   2     120   215    0        1       170     0      0.0    2    0      2       1
116   41    1   2     130   214    0        0       168     0      2.0    1    0      2       1
117   56    1   3     120   193    0        0       162     0      1.9    1    0      3       1
118   46    0   1     105   204    0        1       172     0      0.0    2    0      2       1
119   46    0   0     138   243    0        0       152     1      0.0    1    0      2       1
120   64    0   0     130   303    0        1       122     0      2.0    1    2      2       1
121   59    1   0     138   271    0        0       182     0      0.0    2    0      2       1
122   41    0   2     112   268    0        0       172     1      0.0    2    0      2       1
123   54    0   2     108   267    0        0       167     0      0.0    2    0      2       1
124   39    0   2      94   199    0        1       179     0      0.0    2    0      2       1
125   34    0   1     118   210    0        1       192     0      0.7    2    0      2       1
126   47    1   0     112   204    0        1       143     0      0.1    2    0      2       1
127   67    0   2     152   277    0        1       172     0      0.0    2    1      2       1
128   52    0   2     136   196    0        0       169     0      0.1    1    0      2       1
129   74    0   1     120   269    0        0       121     1      0.2    2    1      2       1
130   54    0   2     160   201    0        1       163     0      0.0    2    1      2       1
131   49    0   1     134   271    0        1       162     0      0.0    1    0      2       1
132   42    1   1     120   295    0        1       162     0      0.0    2    0      2       1
133   41    1   1     110   235    0        1       153     0      0.0    2    0      2       1
134   41    0   1     126   306    0        1       163     0      0.0    2    0      2       1
135   49    0   0     130   269    0        1       163     0      0.0    2    0      2       1
136   60    0   2     120   178    1        1        96     0      0.0    2    0      2       1
137   62    1   1     128   208    1        0       140     0      0.0    2    0      2       1
138   57    1   0     110   201    0        1       126     1      1.5    1    0      1       1
139   64    1   0     128   263    0        1       105     1      0.2    1    1      3       1
140   51    0   2     120   295    0        0       157     0      0.6    2    0      2       1
141   43    1   0     115   303    0        1       181     0      1.2    1    0      2       1
142   42    0   2     120   209    0        1       173     0      0.0    1    0      2       1
143   67    0   0     106   223    0        1       142     0      0.3    2    2      2       1
144   76    0   2     140   197    0        2       116     0      1.1    1    0      2       1
145   70    1   1     156   245    0        0       143     0      0.0    2    0      2       1
146   44    0   2     118   242    0        1       149     0      0.3    1    1      2       1
147   60    0   3     150   240    0        1       171     0      0.9    2    0      2       1
148   44    1   2     120   226    0        1       169     0      0.0    2    0      2       1
149   42    1   2     130   180    0        1       150     0      0.0    2    0      2       1
150   66    1   0     160   228    0        0       138     0      2.3    2    0      1       1
151   71    0   0     112   149    0        1       125     0      1.6    1    0      2       1
152   64    1   3     170   227    0        0       155     0      0.6    1    0      3       1
153   66    0   2     146   278    0        0       152     0      0.0    1    1      2       1
154   39    0   2     138   220    0        1       152     0      0.0    1    0      2       1
155   58    0   0     130   197    0        1       131     0      0.6    1    0      2       1
156   47    1   2     130   253    0        1       179     0      0.0    2    0      2       1
157   35    1   1     122   192    0        1       174     0      0.0    2    0      2       1
158   58    1   1     125   220    0        1       144     0      0.4    1    4      3       1
159   56    1   1     130   221    0        0       163     0      0.0    2    0      3       1
160   56    1   1     120   240    0        1       169     0      0.0    0    0      2       1
161   55    0   1     132   342    0        1       166     0      1.2    2    0      2       1
162   41    1   1     120   157    0        1       182     0      0.0    2    0      2       1
163   38    1   2     138   175    0        1       173     0      0.0    2    4      2       1
164   38    1   2     138   175    0        1       173     0      0.0    2    4      2       1
165   67    1   0     160   286    0        0       108     1      1.5    1    3      2       0
166   67    1   0     120   229    0        0       129     1      2.6    1    2      3       0
167   62    0   0     140   268    0        0       160     0      3.6    0    2      2       0
168   63    1   0     130   254    0        0       147     0      1.4    1    1      3       0
169   53    1   0     140   203    1        0       155     1      3.1    0    0      3       0
170   56    1   2     130   256    1        0       142     1      0.6    1    1      1       0
171   48    1   1     110   229    0        1       168     0      1.0    0    0      3       0
172   58    1   1     120   284    0        0       160     0      1.8    1    0      2       0
173   58    1   2     132   224    0        0       173     0      3.2    2    2      3       0
174   60    1   0     130   206    0        0       132     1      2.4    1    2      3       0
175   40    1   0     110   167    0        0       114     1      2.0    1    0      3       0
176   60    1   0     117   230    1        1       160     1      1.4    2    2      3       0
177   64    1   2     140   335    0        1       158     0      0.0    2    0      2       0
178   43    1   0     120   177    0        0       120     1      2.5    1    0      3       0
179   57    1   0     150   276    0        0       112     1      0.6    1    1      1       0
180   55    1   0     132   353    0        1       132     1      1.2    1    1      3       0
181   65    0   0     150   225    0        0       114     0      1.0    1    3      3       0
182   61    0   0     130   330    0        0       169     0      0.0    2    0      2       0
183   58    1   2     112   230    0        0       165     0      2.5    1    1      3       0
184   50    1   0     150   243    0        0       128     0      2.6    1    0      3       0
185   44    1   0     112   290    0        0       153     0      0.0    2    1      2       0
186   60    1   0     130   253    0        1       144     1      1.4    2    1      3       0
187   54    1   0     124   266    0        0       109     1      2.2    1    1      3       0
188   50    1   2     140   233    0        1       163     0      0.6    1    1      3       0
189   41    1   0     110   172    0        0       158     0      0.0    2    0      3       0
190   51    0   0     130   305    0        1       142     1      1.2    1    0      3       0
191   58    1   0     128   216    0        0       131     1      2.2    1    3      3       0
192   54    1   0     120   188    0        1       113     0      1.4    1    1      3       0
193   60    1   0     145   282    0        0       142     1      2.8    1    2      3       0
194   60    1   2     140   185    0        0       155     0      3.0    1    0      2       0
195   59    1   0     170   326    0        0       140     1      3.4    0    0      3       0
196   46    1   2     150   231    0        1       147     0      3.6    1    0      2       0
197   67    1   0     125   254    1        1       163     0      0.2    1    2      3       0
198   62    1   0     120   267    0        1        99     1      1.8    1    2      3       0
199   65    1   0     110   248    0        0       158     0      0.6    2    2      1       0
200   44    1   0     110   197    0        0       177     0      0.0    2    1      2       0
201   60    1   0     125   258    0        0       141     1      2.8    1    1      3       0
202   58    1   0     150   270    0        0       111     1      0.8    2    0      3       0
203   68    1   2     180   274    1        0       150     1      1.6    1    0      3       0
204   62    0   0     160   164    0        0       145     0      6.2    0    3      3       0
205   52    1   0     128   255    0        1       161     1      0.0    2    1      3       0
206   59    1   0     110   239    0        0       142     1      1.2    1    1      3       0

# Pandas Methods

In [24]:
df.head()#print first 5 records

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [25]:
df.tail()#print last 5 records

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [26]:
df.head(10)#print first 10 records

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [27]:
df.describe()# info about the dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [29]:
df.shape # shows the rows and columns

(303, 14)

In [30]:
df[5:50:3] # [start:stop:difference]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
20,59,1,0,135,234,0,1,161,0,0.5,1,0,3,1
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2,1
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2,1
32,44,1,1,130,219,0,0,188,0,0.0,2,0,2,1
35,46,0,2,142,177,0,0,160,1,1.4,0,0,2,1
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
41,48,1,1,130,245,0,0,180,0,0.2,1,0,2,1
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2,1
47,47,1,2,138,257,0,0,156,0,0.0,2,0,2,1

In [31]:
df["age"]

0      63
1      37
2      41
3      56
4      57
5      57
6      56
7      44
8      52
9      57
10     54
11     48
12     49
13     64
14     58
15     50
16     58
17     66
18     43
19     69
20     59
21     44
22     42
23     61
24     40
25     71
26     59
27     51
28     65
29     53
       ..
273    58
274    47
275    52
276    58
277    57
278    58
279    61
280    42
281    52
282    59
283    40
284    61
285    46
286    59
287    57
288    57
289    55
290    61
291    58
292    58
293    67
294    44
295    63
296    63
297    59
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [32]:
#loc is used to print the row of the dataset
df.loc[0]

age          63.0
sex           1.0
cp            3.0
trtbps      145.0
chol        233.0
fbs           1.0
restecg       0.0
thalachh    150.0
exng          0.0
oldpeak       2.3
slp           0.0
caa           0.0
thall         1.0
output        1.0
Name: 0, dtype: float64

In [41]:
df.loc[0:5]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [54]:
# retrieve the data with specified rows and columns
#stop index included in loc
#columns are accessed by column names
df.loc[0:5,["age","sex"]]

   age  sex
0   63    1
1   37    1
2   41    0
3   56    1
4   57    0
5   57    1

In [53]:
# retrieve the data for specified range of the columns
df.loc[0,"age":"fbs"]

age        63.0
sex         1.0
cp          3.0
trtbps    145.0
chol      233.0
fbs         1.0
Name: 0, dtype: float64

In [44]:
#iloc[] stop index excluded in iloc
#columns are accessed by indexes
df.iloc[1:6]

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1

In [59]:
df.iloc[3,2]#[row,column index]

1

In [60]:
df.iloc[3:5,7:10]

   thalachh  exng  oldpeak
3       178     0      0.8
4       163     1      0.6

In [61]:
df.iloc[[1,3,5,7,8]]#[[]] used for accessing only rows for the dataset

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1

In [64]:
df.iloc[:,[1,4,5,6,7]]#:, is used for accesing only columns of the dataset

     sex  chol  fbs  restecg  thalachh
0      1   233    1        0       150
1      1   250    0        1       187
2      0   204    0        0       172
3      1   236    0        1       178
4      0   354    0        1       163
5      1   192    0        1       148
6      0   294    0        0       153
7      1   263    0        1       173
8      1   199    1        1       162
9      1   168    0        1       174
10     1   239    0        1       160
11     0   275    0        1       139
12     1   266    0        1       171
13     1   211    0        0       144
14     0   283    1        0       162
15     0   219    0        1       158
16     0   340    0        1       172
17     0   226    0        1       114
18     1   247    0        1       171
19     0   239    0        1       151
20     1   234    0        1       161
21     1   233    0        1       179
22     1   226    0        1       178
23     1   243    1        1       137
24     1   199    0        1       178
25     0   302    0        1       162
26     1   212    1        1       157
27     1   175    0        1       123
28     0   417    1        0       157
29     1   197    1        0       152
..   ...   ...  ...      ...       ...
273    1   234    0        1       156
274    1   275    0        0       118
275    1   212    0        1       168
276    1   218    0        1       105
277    1   261    0        1       141
278    0   319    1        0       152
279    1   166    0        0       125
280    1   315    0        1       125
281    1   204    1        1       156
282    1   218    1        1       134
283    1   223    0        1       181
284    1   207    0        0       138
285    1   311    0        1       120
286    1   204    0        1       162
287    1   232    0        0       164
288    1   335    0        1       143
289    0   205    0        2       130
290    1   203    0        1       161
291    1   318    0        2       140
292    0   225    1        0       146
293    1   212    0        0       150
294    1   169    0        1       144
295    1   187    0        0       144
296    0   197    0        1       136
297    1   176    1        0        90
298    0   241    0        1       123
299    1   264    0        1       132
300    1   193    1        1       141
301    1   131    0        1       115
302    0   236    0        0       174

[303 rows x 5 columns]

In [66]:
df.iloc[[1,2,3],[1,3,5]]#rows,columns

   sex  trtbps  fbs
1    1     130    0
2    0     130    0
3    1     120    0

# Sorting DataFrames

In [76]:
df.sort_values("age")

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output,mani
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1,14
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1,14
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1,14
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0,14
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1,14
227,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0,14
157,35,1,1,122,192,0,1,174,0,0.0,2,0,2,1,14
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,14
115,37,0,2,120,215,0,1,170,0,0.0,2,0,2,1,14
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1,14
163,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1,14
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3,0,14
154,39,0,2,138,220,0,1,152,0,0.0,1,0,2,1,14
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2,1,14
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3,0,14
124,39,0,2,94,199,0,1,179,0,0.0,2,0,2,1,14
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1,14
175,40,1,0,110,167,0,0,114,1,2.0,1,0,3,0,14
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3,0,14
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2,1,14
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2,1,14
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2,1,14
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2,1,14
162,41,1,1,120,157,0,1,182,0,0.0,2,0,2,1,14
63,41,1,1,135,203,0,1,132,0,0.0,1,0,1,1,14
122,41,0,2,112,268,0,0,172,1,0.0,2,0,2,1,14
80,41,1,2,112,250,0,1,179,0,0.0,2,0,2,1,14
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,14
189,41,1,0,110,172,0,0,158,0,0.0,2,0,3,0,14
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1,14
265,66,1,0,112,212,0,0,132,1,0.1,2,1,2,0,14
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1,14
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0,14
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0,14
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1,14
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2,0,14
253,67,1,0,100,299,0,0,125,1,0.9,1,2,2,0,14
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3,0,14
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1,14
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3,0,14
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1,14
165,67,1,0,160,286,0,0,108,1,1.5,1,3,2,0,14
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3,0,14
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1,14
86,68,1,2,118,277,0,1,151,0,1.0,2,1,3,1,14
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,14
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1,14
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2,1,14
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3,0,14
145,70,1,1,156,245,0,0,143,0,0.0,2,0,2,1,14
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0,14
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0,14
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0,14
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1,14
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1,14
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1,14
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1,14
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1,14
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0,14

In [77]:
df.sort_values("age",ascending=False)

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output,mani
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0,14
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1,14
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1,14
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1,14
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1,14
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1,14
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0,14
145,70,1,1,156,245,0,0,143,0,0.0,2,0,2,1,14
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0,14
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0,14
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2,1,14
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3,0,14
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1,14
86,68,1,2,118,277,0,1,151,0,1.0,2,1,3,1,14
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1,14
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3,0,14
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,14
165,67,1,0,160,286,0,0,108,1,1.5,1,3,2,0,14
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3,0,14
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1,14
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0,14
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1,14
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2,0,14
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3,0,14
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1,14
253,67,1,0,100,299,0,0,125,1,0.9,1,2,2,0,14
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0,14
51,66,1,0,120,302,0,0,151,0,0.4,1,0,2,1,14
265,66,1,0,112,212,0,0,132,1,0.1,2,1,2,0,14
150,66,1,0,160,228,0,0,138,0,2.3,2,0,1,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,42,0,2,120,209,0,1,173,0,0.0,1,0,2,1,14
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2,1,14
162,41,1,1,120,157,0,1,182,0,0.0,2,0,2,1,14
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2,1,14
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2,1,14
80,41,1,2,112,250,0,1,179,0,0.0,2,0,2,1,14
63,41,1,1,135,203,0,1,132,0,0.0,1,0,1,1,14
122,41,0,2,112,268,0,0,172,1,0.0,2,0,2,1,14
189,41,1,0,110,172,0,0,158,0,0.0,2,0,3,0,14
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,14
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2,1,14
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1,14
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3,0,14
175,40,1,0,110,167,0,0,114,1,2.0,1,0,3,0,14
124,39,0,2,94,199,0,1,179,0,0.0,2,0,2,1,14
154,39,0,2,138,220,0,1,152,0,0.0,1,0,2,1,14
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2,1,14
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3,0,14
163,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1,14
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3,0,14
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1,14
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,14
115,37,0,2,120,215,0,1,170,0,0.0,2,0,2,1,14
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1,14
157,35,1,1,122,192,0,1,174,0,0.0,2,0,2,1,14
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0,14
227,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0,14
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1,14
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1,14
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1,14

In [81]:
df.sort_values("fbs")

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output,mani
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1,14
180,55,1,0,132,353,0,1,132,1,1.2,1,1,3,0,14
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3,0,14
182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0,14
183,58,1,2,112,230,0,0,165,0,2.5,1,1,3,0,14
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3,0,14
185,44,1,0,112,290,0,0,153,0,0.0,2,1,2,0,14
186,60,1,0,130,253,0,1,144,1,1.4,2,1,3,0,14
187,54,1,0,124,266,0,0,109,1,2.2,1,1,3,0,14
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3,0,14
189,41,1,0,110,172,0,0,158,0,0.0,2,0,3,0,14
190,51,0,0,130,305,0,1,142,1,1.2,1,0,3,0,14
191,58,1,0,128,216,0,0,131,1,2.2,1,3,3,0,14
192,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0,14
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3,0,14
194,60,1,2,140,185,0,0,155,0,3.0,1,0,2,0,14
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3,0,14
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2,0,14
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3,0,14
211,61,1,0,120,260,0,1,140,1,3.6,1,1,3,0,14
210,57,1,2,128,229,0,0,150,0,0.4,1,1,3,0,14
209,59,1,0,140,177,0,1,162,1,0.0,2,1,3,0,14
208,49,1,2,120,188,0,1,139,0,2.0,1,3,3,0,14
207,60,0,0,150,258,0,0,157,0,2.6,1,2,3,0,14
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1,0,14
206,59,1,0,110,239,0,0,142,1,1.2,1,1,3,0,14
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0,14
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3,0,14
201,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0,14
200,44,1,0,110,197,0,0,177,0,0.0,2,1,2,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0,14
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3,0,14
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1,14
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1,14
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2,1,14
64,58,1,2,140,211,1,0,165,0,0.0,2,0,2,1,14
97,52,1,0,108,233,1,1,147,0,0.1,2,3,3,1,14
103,42,1,2,120,240,1,1,194,0,0.8,0,0,3,1,14
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3,0,14
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2,1,14
251,43,1,0,132,247,1,0,143,1,0.1,1,4,3,0,14
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0,14
93,54,0,1,132,288,1,0,159,1,0.0,2,1,2,1,14
76,51,1,2,125,245,1,0,166,0,2.4,1,0,2,1,14
36,54,0,2,135,304,1,1,170,0,0.0,2,0,2,1,14
170,56,1,2,130,256,1,0,142,1,0.6,1,1,1,0,14
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3,0,14
169,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0,14
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3,1,14
90,48,1,2,124,255,1,1,175,0,0.0,2,2,2,1,14
231,57,1,0,165,289,1,0,124,0,1.0,1,3,3,0,14
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2,1,14
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1,14
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1,14
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2,1,14
269,56,1,0,130,283,1,0,103,1,1.6,0,0,3,0,14
87,46,1,1,101,197,1,1,156,0,0.0,2,0,3,1,14
99,53,1,2,130,246,1,0,173,0,0.0,2,3,2,1,14
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0,14
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,14

In [83]:
df.sort_values(["age","fbs"])

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output,mani
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2,1,14
58,34,1,3,118,182,0,0,174,0,0.0,2,0,2,1,14
125,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1,14
65,35,0,0,138,183,0,1,182,0,1.4,2,0,2,1,14
157,35,1,1,122,192,0,1,174,0,0.0,2,0,2,1,14
227,35,1,0,120,198,0,1,130,1,1.6,1,0,3,0,14
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0,14
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1,14
115,37,0,2,120,215,0,1,170,0,0.0,2,0,2,1,14
163,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1,14
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1,14
259,38,1,3,120,231,0,1,182,1,3.8,1,0,3,0,14
44,39,1,2,140,321,0,0,182,0,0.0,2,0,2,1,14
124,39,0,2,94,199,0,1,179,0,0.0,2,0,2,1,14
154,39,0,2,138,220,0,1,152,0,0.0,1,0,2,1,14
212,39,1,0,118,219,0,1,140,0,1.2,1,0,3,0,14
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3,1,14
175,40,1,0,110,167,0,0,114,1,2.0,1,0,3,0,14
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3,0,14
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1,14
30,41,0,1,105,198,0,1,168,0,0.0,2,1,2,1,14
63,41,1,1,135,203,0,1,132,0,0.0,1,0,1,1,14
80,41,1,2,112,250,0,1,179,0,0.0,2,0,2,1,14
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2,1,14
122,41,0,2,112,268,0,0,172,1,0.0,2,0,2,1,14
133,41,1,1,110,235,0,1,153,0,0.0,2,0,2,1,14
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2,1,14
162,41,1,1,120,157,0,1,182,0,0.0,2,0,2,1,14
189,41,1,0,110,172,0,0,158,0,0.0,2,0,3,0,14
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1,14
247,66,1,1,160,246,0,1,120,1,0.0,1,3,1,0,14
265,66,1,0,112,212,0,0,132,1,0.1,2,1,2,0,14
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0,14
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1,14
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1,14
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1,14
165,67,1,0,160,286,0,0,108,1,1.5,1,3,2,0,14
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3,0,14
253,67,1,0,100,299,0,0,125,1,0.9,1,2,2,0,14
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2,0,14
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3,0,14
197,67,1,0,125,254,1,1,163,0,0.2,1,2,3,0,14
86,68,1,2,118,277,0,1,151,0,1.0,2,1,3,1,14
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1,14
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3,0,14
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,14
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1,14
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3,0,14
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2,1,14
145,70,1,1,156,245,0,0,143,0,0.0,2,0,2,1,14
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0,14
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0,14
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0,14
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1,14
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1,14
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1,14
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1,14
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1,14
238,77,1,0,125,304,0,0,162,1,0.0,2,3,2,0,14

In [94]:
df.loc[(df["age"]>60) & (df["oldpeak"]>1)]#conditions

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output,mani
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1,14
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1,14
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1,14
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1,14
52,62,1,2,130,231,0,1,146,0,1.8,1,3,3,1,14
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1,14
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1,14
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1,14
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1,14
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1,14
150,66,1,0,160,228,0,0,138,0,2.3,2,0,1,1,14
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1,14
165,67,1,0,160,286,0,0,108,1,1.5,1,3,2,0,14
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3,0,14
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0,14
168,63,1,0,130,254,0,0,147,0,1.4,1,1,3,0,14
198,62,1,0,120,267,0,1,99,1,1.8,1,2,3,0,14
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3,0,14
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0,14
211,61,1,0,120,260,0,1,140,1,3.6,1,1,3,0,14
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0,14
217,63,1,0,130,330,1,0,132,1,1.8,2,3,3,0,14
218,65,1,0,135,254,0,0,127,0,2.8,1,1,3,0,14
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0,14
222,65,1,3,138,282,1,0,174,0,1.4,1,1,2,0,14
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0,14
226,62,1,1,120,281,0,0,103,0,1.4,1,1,3,0,14
229,64,1,2,125,309,0,1,131,1,1.8,1,0,3,0,14
233,64,1,0,120,246,0,0,96,1,2.2,0,1,2,0,14
234,70,1,0,130,322,0,0,109,0,2.4,1,3,2,0,14
240,70,1,2,160,269,0,1,112,1,2.9,1,1,3,0,14
242,64,1,0,145,212,0,0,132,0,2.0,1,2,1,0,14
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3,0,14
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0,14
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2,0,14
263,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0,14
271,61,1,3,134,234,0,1,145,0,2.6,1,2,2,0,14
279,61,1,0,138,166,0,0,125,1,3.6,1,1,2,0,14
284,61,1,0,140,207,0,0,138,1,1.9,2,1,3,0,14
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3,0,14
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0,14

# String Functions

In [97]:
import pandas as pd
df=pd.read_csv("canadian_immegration_data.csv")
df

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15
5,Angola,Africa,Middle Africa,Developing regions,1,3,6,6,4,3,...,295,184,106,76,62,61,39,70,45,2113
6,Antigua and Barbuda,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,42,52,...,24,32,15,32,38,27,37,51,25,981
7,Argentina,Latin America and the Caribbean,South America,Developing regions,368,426,626,241,237,196,...,1153,847,620,540,467,459,278,263,282,19596
8,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,224,218,198,205,267,252,236,258,207,3310
9,Australia,Oceania,Australia and New Zealand,Developed regions,702,639,484,317,317,319,...,909,875,1033,1018,1018,933,851,982,1121,23829
10,Austria,Europe,Western Europe,Developed regions,234,238,201,117,127,165,...,122,102,98,91,109,124,84,102,90,4985
11,Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,359,236,203,125,165,209,138,161,57,2649
12,Bahamas,Latin America and the Caribbean,Caribbean,Developing regions,26,23,38,12,21,28,...,14,18,23,30,27,25,40,60,55,808
13,Bahrain,Asia,Western Asia,Developing regions,0,2,1,1,1,3,...,12,12,22,9,35,28,21,39,32,475
14,Bangladesh,Asia,Southern Asia,Developing regions,83,84,86,81,98,92,...,4171,4014,2897,2939,2104,4721,2694,2640,3789,65568
15,Barbados,Latin America and the Caribbean,Caribbean,Developing regions,372,376,299,244,265,285,...,111,97,130,134,125,121,97,132,97,6923
16,Belarus,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,558,439,568,524,454,438,357,277,247,7975
17,Belgium,Europe,Western Europe,Developed regions,511,540,519,297,183,181,...,400,302,363,335,358,363,332,402,379,10762
18,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,...,37,24,28,48,38,39,36,34,53,1083
19,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,...,95,116,183,205,238,290,284,391,397,2852
20,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,...,5,10,7,36,865,1464,1879,1075,487,5876
21,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,...,134,139,107,143,214,180,86,83,107,3205
22,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,211,217,209,182,156,168,140,121,119,21855
23,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,...,7,11,8,28,15,42,53,64,76,396
24,Brazil,Latin America and the Caribbean,South America,Developing regions,211,220,192,139,145,130,...,969,1181,1746,2138,2509,2598,1508,1642,1714,29659
25,Brunei Darussalam,Asia,South-Eastern Asia,Developing regions,79,6,8,2,2,4,...,4,5,11,10,5,12,6,3,6,600
26,Bulgaria,Europe,Eastern Europe,Developed regions,24,20,12,33,11,24,...,1738,1419,1172,994,784,556,365,451,512,23310
27,Burkina Faso,Africa,Western Africa,Developing regions,2,1,3,2,3,2,...,91,147,136,139,162,186,144,269,322,2043
28,Burundi,Africa,Eastern Africa,Developing regions,0,0,0,0,1,2,...,626,468,614,448,566,529,604,684,480,8110
29,Cabo Verde,Africa,Western Africa,Developing regions,1,1,2,0,11,1,...,5,7,2,5,1,3,3,6,2,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Suriname,Latin America and the Caribbean,South America,Developing regions,15,10,21,12,5,16,...,15,16,20,9,12,13,11,16,4,739
166,Swaziland,Africa,Southern Africa,Developing regions,4,1,1,0,10,7,...,7,7,5,6,10,3,13,17,39,188
167,Sweden,Europe,Northern Europe,Developed regions,281,308,222,176,128,158,...,205,139,193,165,167,159,134,140,140,5866
168,Switzerland,Europe,Western Europe,Developed regions,806,811,634,370,326,314,...,270,258,308,357,328,285,266,243,201,15678
169,Syrian Arab Republic,Asia,Western Asia,Developing regions,315,419,409,269,264,385,...,1458,1145,1056,919,917,1039,1005,650,1009,31485
170,Tajikistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,85,46,44,15,50,52,47,34,39,503
171,Thailand,Asia,South-Eastern Asia,Developing regions,56,53,113,65,82,66,...,575,500,487,519,512,499,396,296,400,9174
172,The former Yugoslav Republic of Macedonia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,285,256,211,191,198,188,130,126,112,4637
173,Togo,Africa,Western Africa,Developing regions,5,5,2,3,6,5,...,157,149,235,351,400,354,261,299,316,3545
174,Tonga,Oceania,Polynesia,Developing regions,2,4,7,1,2,5,...,2,0,1,0,5,5,2,3,5,142
175,Trinidad and Tobago,Latin America and the Caribbean,Caribbean,Developing regions,958,947,972,766,606,699,...,857,794,975,1002,1134,915,588,586,427,50016
176,Tunisia,Africa,Northern Africa,Developing regions,58,51,55,46,51,57,...,756,1065,869,950,1195,1299,1442,1503,1627,17583
177,Turkey,Asia,Western Asia,Developing regions,481,874,706,280,338,202,...,2065,1638,1463,1122,1238,1492,1257,1068,729,31781
178,Turkmenistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,40,26,37,13,20,30,20,20,14,310
179,Tuvalu,Oceania,Polynesia,Developing regions,0,1,0,0,1,0,...,0,0,1,0,0,0,1,0,0,8
180,Uganda,Africa,Eastern Africa,Developing regions,13,16,17,38,32,29,...,239,201,170,204,185,216,213,222,206,3450
181,Ukraine,Europe,Eastern Europe,Developed regions,0,0,0,0,0,0,...,2270,1973,2218,1937,2367,3159,2515,2265,2487,51410
182,United Arab Emirates,Asia,Western Asia,Developing regions,0,2,2,1,2,0,...,31,42,37,33,37,86,60,54,46,836
183,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,Developed regions,22045,24796,20620,10015,10170,9564,...,7258,7140,8216,8979,8876,8724,6204,6195,5827,551500
184,United Republic of Tanzania,Africa,Eastern Africa,Developing regions,635,832,621,474,473,460,...,274,291,195,230,136,200,215,224,182,12496
185,United States of America,Northern America,Northern America,Developed regions,9378,10030,9074,7100,6661,6543,...,8394,9613,9463,10190,8995,8142,7676,7891,8501,241122
186,Uruguay,Latin America and the Caribbean,South America,Developing regions,128,132,146,105,90,92,...,217,175,147,160,99,93,81,47,58,4715
187,Uzbekistan,Asia,Central Asia,Developing regions,0,0,0,0,0,0,...,330,262,284,215,288,289,162,235,167,3368
188,Vanuatu,Oceania,Melanesia,Developing regions,0,0,0,0,0,0,...,1,1,0,0,1,0,0,0,0,11
189,Venezuela (Bolivarian Republic of),Latin America and the Caribbean,South America,Developing regions,103,117,174,124,142,165,...,1211,1192,1335,1239,1353,998,1452,1373,1022,21267
190,Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146
191,Western Sahara,Africa,Northern Africa,Developing regions,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,2
192,Yemen,Asia,Western Asia,Developing regions,1,2,1,6,0,18,...,161,140,122,133,128,211,160,174,217,2985
193,Zambia,Africa,Eastern Africa,Developing regions,11,17,11,7,16,9,...,91,77,71,64,60,102,69,46,59,1677
194,Zimbabwe,Africa,Eastern Africa,Developing regions,72,114,102,44,32,29,...,615,454,663,611,508,494,434,437,407,8598

In [98]:
df.loc[df["Country"].str.contains("go")]

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
5,Angola,Africa,Middle Africa,Developing regions,1,3,6,6,4,3,...,295,184,106,76,62,61,39,70,45,2113
22,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,211,217,209,182,156,168,140,121,119,21855
41,Congo,Africa,Middle Africa,Developing regions,2,0,1,0,1,2,...,136,143,87,72,70,75,81,91,114,1686
49,Democratic Republic of the Congo,Africa,Middle Africa,Developing regions,15,16,17,17,28,11,...,1521,1623,1466,1397,1581,1239,1224,1714,2050,25582
114,Mongolia,Asia,Eastern Asia,Developing regions,0,0,0,0,0,0,...,59,64,82,59,118,169,103,68,99,952
172,The former Yugoslav Republic of Macedonia,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,285,256,211,191,198,188,130,126,112,4637
173,Togo,Africa,Western Africa,Developing regions,5,5,2,3,6,5,...,157,149,235,351,400,354,261,299,316,3545
175,Trinidad and Tobago,Latin America and the Caribbean,Caribbean,Developing regions,958,947,972,766,606,699,...,857,794,975,1002,1134,915,588,586,427,50016

In [103]:
df.loc[df["Country"].str.startswith("A")]

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15
5,Angola,Africa,Middle Africa,Developing regions,1,3,6,6,4,3,...,295,184,106,76,62,61,39,70,45,2113
6,Antigua and Barbuda,Latin America and the Caribbean,Caribbean,Developing regions,0,0,0,0,42,52,...,24,32,15,32,38,27,37,51,25,981
7,Argentina,Latin America and the Caribbean,South America,Developing regions,368,426,626,241,237,196,...,1153,847,620,540,467,459,278,263,282,19596
8,Armenia,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,224,218,198,205,267,252,236,258,207,3310
9,Australia,Oceania,Australia and New Zealand,Developed regions,702,639,484,317,317,319,...,909,875,1033,1018,1018,933,851,982,1121,23829
10,Austria,Europe,Western Europe,Developed regions,234,238,201,117,127,165,...,122,102,98,91,109,124,84,102,90,4985
11,Azerbaijan,Asia,Western Asia,Developing regions,0,0,0,0,0,0,...,359,236,203,125,165,209,138,161,57,2649

In [104]:
import pandas as pd
df=pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61
20,male,group D,high school,standard,none,66,69,63
21,female,group B,some college,free/reduced,completed,65,75,70
22,male,group D,some college,standard,none,44,54,53
23,female,group C,some high school,standard,none,69,73,73
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
25,male,group A,master's degree,free/reduced,none,73,74,72
26,male,group B,some college,standard,none,69,54,55
27,female,group C,bachelor's degree,standard,none,67,69,75
28,male,group C,high school,standard,none,70,70,65
29,female,group D,master's degree,standard,none,62,70,75
...,...,...,...,...,...,...,...,...
970,female,group D,bachelor's degree,standard,none,89,100,100
971,male,group C,some high school,standard,completed,78,72,69
972,female,group A,high school,free/reduced,completed,53,50,60
973,female,group D,some college,free/reduced,none,49,65,61
974,female,group A,some college,standard,none,54,63,67
975,female,group C,some college,standard,completed,64,82,77
976,male,group B,some college,free/reduced,completed,60,62,60
977,male,group C,associate's degree,standard,none,62,65,58
978,male,group D,high school,standard,completed,55,41,48
979,female,group C,associate's degree,standard,none,91,95,94
980,female,group B,high school,free/reduced,none,8,24,23
981,male,group D,some high school,standard,none,81,78,78
982,male,group B,some high school,standard,completed,79,85,86
983,female,group A,some college,standard,completed,78,87,91
984,female,group C,some high school,standard,none,74,75,82
985,male,group A,high school,standard,none,57,51,54
986,female,group C,associate's degree,standard,none,40,59,51
987,male,group E,some high school,standard,completed,81,75,76
988,female,group A,some high school,free/reduced,none,44,45,45
989,female,group D,some college,free/reduced,completed,67,86,83
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [106]:
df["result"]="pass/fail"
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,result
0,female,group B,bachelor's degree,standard,none,72,72,74,pass/fail
1,female,group C,some college,standard,completed,69,90,88,pass/fail
2,female,group B,master's degree,standard,none,90,95,93,pass/fail
3,male,group A,associate's degree,free/reduced,none,47,57,44,pass/fail
4,male,group C,some college,standard,none,76,78,75,pass/fail
5,female,group B,associate's degree,standard,none,71,83,78,pass/fail
6,female,group B,some college,standard,completed,88,95,92,pass/fail
7,male,group B,some college,free/reduced,none,40,43,39,pass/fail
8,male,group D,high school,free/reduced,completed,64,64,67,pass/fail
9,female,group B,high school,free/reduced,none,38,60,50,pass/fail
10,male,group C,associate's degree,standard,none,58,54,52,pass/fail
11,male,group D,associate's degree,standard,none,40,52,43,pass/fail
12,female,group B,high school,standard,none,65,81,73,pass/fail
13,male,group A,some college,standard,completed,78,72,70,pass/fail
14,female,group A,master's degree,standard,none,50,53,58,pass/fail
15,female,group C,some high school,standard,none,69,75,78,pass/fail
16,male,group C,high school,standard,none,88,89,86,pass/fail
17,female,group B,some high school,free/reduced,none,18,32,28,pass/fail
18,male,group C,master's degree,free/reduced,completed,46,42,46,pass/fail
19,female,group C,associate's degree,free/reduced,none,54,58,61,pass/fail
20,male,group D,high school,standard,none,66,69,63,pass/fail
21,female,group B,some college,free/reduced,completed,65,75,70,pass/fail
22,male,group D,some college,standard,none,44,54,53,pass/fail
23,female,group C,some high school,standard,none,69,73,73,pass/fail
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,pass/fail
25,male,group A,master's degree,free/reduced,none,73,74,72,pass/fail
26,male,group B,some college,standard,none,69,54,55,pass/fail
27,female,group C,bachelor's degree,standard,none,67,69,75,pass/fail
28,male,group C,high school,standard,none,70,70,65,pass/fail
29,female,group D,master's degree,standard,none,62,70,75,pass/fail
...,...,...,...,...,...,...,...,...,...
970,female,group D,bachelor's degree,standard,none,89,100,100,pass/fail
971,male,group C,some high school,standard,completed,78,72,69,pass/fail
972,female,group A,high school,free/reduced,completed,53,50,60,pass/fail
973,female,group D,some college,free/reduced,none,49,65,61,pass/fail
974,female,group A,some college,standard,none,54,63,67,pass/fail
975,female,group C,some college,standard,completed,64,82,77,pass/fail
976,male,group B,some college,free/reduced,completed,60,62,60,pass/fail
977,male,group C,associate's degree,standard,none,62,65,58,pass/fail
978,male,group D,high school,standard,completed,55,41,48,pass/fail
979,female,group C,associate's degree,standard,none,91,95,94,pass/fail
980,female,group B,high school,free/reduced,none,8,24,23,pass/fail
981,male,group D,some high school,standard,none,81,78,78,pass/fail
982,male,group B,some high school,standard,completed,79,85,86,pass/fail
983,female,group A,some college,standard,completed,78,87,91,pass/fail
984,female,group C,some high school,standard,none,74,75,82,pass/fail
985,male,group A,high school,standard,none,57,51,54,pass/fail
986,female,group C,associate's degree,standard,none,40,59,51,pass/fail
987,male,group E,some high school,standard,completed,81,75,76,pass/fail
988,female,group A,some high school,free/reduced,none,44,45,45,pass/fail
989,female,group D,some college,free/reduced,completed,67,86,83,pass/fail
990,male,group E,high school,free/reduced,completed,86,81,75,pass/fail
991,female,group B,some high school,standard,completed,65,82,78,pass/fail
992,female,group D,associate's degree,free/reduced,none,55,76,76,pass/fail
993,female,group D,bachelor's degree,free/reduced,none,62,72,74,pass/fail
994,male,group A,high school,standard,none,63,63,62,pass/fail
995,female,group E,master's degree,standard,completed,88,99,95,pass/fail
996,male,group C,high school,free/reduced,none,62,55,55,pass/fail
997,female,group C,high school,free/reduced,completed,59,71,65,pass/fail
998,female,group D,some college,standard,completed,68,78,77,pass/fail
999,female,group D,some college,free/reduced,none,77,86,86,pass/fail

In [140]:
df["sucess"]="pass/fail"
df.loc[(df["math score"]>40)&(df["writing score"]>50),["result"]]="pass"

In [139]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,result,sucess
0,female,group B,bachelor's degree,standard,none,72,72,74,pass,pass/fail
1,female,group C,some college,standard,completed,69,90,88,pass,pass/fail
2,female,group B,master's degree,standard,none,90,95,93,pass,pass/fail
3,male,group A,associate's degree,free/reduced,none,47,57,44,pass,pass/fail
4,male,group C,some college,standard,none,76,78,75,pass,pass/fail
5,female,group B,associate's degree,standard,none,71,83,78,pass,pass/fail
6,female,group B,some college,standard,completed,88,95,92,pass,pass/fail
7,male,group B,some college,free/reduced,none,40,43,39,fail,pass/fail
8,male,group D,high school,free/reduced,completed,64,64,67,pass,pass/fail
9,female,group B,high school,free/reduced,none,38,60,50,pass,pass/fail
10,male,group C,associate's degree,standard,none,58,54,52,pass,pass/fail
11,male,group D,associate's degree,standard,none,40,52,43,fail,pass/fail
12,female,group B,high school,standard,none,65,81,73,pass,pass/fail
13,male,group A,some college,standard,completed,78,72,70,pass,pass/fail
14,female,group A,master's degree,standard,none,50,53,58,pass,pass/fail
15,female,group C,some high school,standard,none,69,75,78,pass,pass/fail
16,male,group C,high school,standard,none,88,89,86,pass,pass/fail
17,female,group B,some high school,free/reduced,none,18,32,28,pass,pass/fail
18,male,group C,master's degree,free/reduced,completed,46,42,46,pass,pass/fail
19,female,group C,associate's degree,free/reduced,none,54,58,61,pass,pass/fail
20,male,group D,high school,standard,none,66,69,63,pass,pass/fail
21,female,group B,some college,free/reduced,completed,65,75,70,pass,pass/fail
22,male,group D,some college,standard,none,44,54,53,pass,pass/fail
23,female,group C,some high school,standard,none,69,73,73,pass,pass/fail
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,pass,pass/fail
25,male,group A,master's degree,free/reduced,none,73,74,72,pass,pass/fail
26,male,group B,some college,standard,none,69,54,55,pass,pass/fail
27,female,group C,bachelor's degree,standard,none,67,69,75,pass,pass/fail
28,male,group C,high school,standard,none,70,70,65,pass,pass/fail
29,female,group D,master's degree,standard,none,62,70,75,pass,pass/fail
...,...,...,...,...,...,...,...,...,...,...
970,female,group D,bachelor's degree,standard,none,89,100,100,pass,pass/fail
971,male,group C,some high school,standard,completed,78,72,69,pass,pass/fail
972,female,group A,high school,free/reduced,completed,53,50,60,pass,pass/fail
973,female,group D,some college,free/reduced,none,49,65,61,pass,pass/fail
974,female,group A,some college,standard,none,54,63,67,pass,pass/fail
975,female,group C,some college,standard,completed,64,82,77,pass,pass/fail
976,male,group B,some college,free/reduced,completed,60,62,60,pass,pass/fail
977,male,group C,associate's degree,standard,none,62,65,58,pass,pass/fail
978,male,group D,high school,standard,completed,55,41,48,pass,pass/fail
979,female,group C,associate's degree,standard,none,91,95,94,pass,pass/fail
980,female,group B,high school,free/reduced,none,8,24,23,pass,pass/fail
981,male,group D,some high school,standard,none,81,78,78,pass,pass/fail
982,male,group B,some high school,standard,completed,79,85,86,pass,pass/fail
983,female,group A,some college,standard,completed,78,87,91,pass,pass/fail
984,female,group C,some high school,standard,none,74,75,82,pass,pass/fail
985,male,group A,high school,standard,none,57,51,54,pass,pass/fail
986,female,group C,associate's degree,standard,none,40,59,51,fail,pass/fail
987,male,group E,some high school,standard,completed,81,75,76,pass,pass/fail
988,female,group A,some high school,free/reduced,none,44,45,45,pass,pass/fail
989,female,group D,some college,free/reduced,completed,67,86,83,pass,pass/fail
990,male,group E,high school,free/reduced,completed,86,81,75,pass,pass/fail
991,female,group B,some high school,standard,completed,65,82,78,pass,pass/fail
992,female,group D,associate's degree,free/reduced,none,55,76,76,pass,pass/fail
993,female,group D,bachelor's degree,free/reduced,none,62,72,74,pass,pass/fail
994,male,group A,high school,standard,none,63,63,62,pass,pass/fail
995,female,group E,master's degree,standard,completed,88,99,95,pass,pass/fail
996,male,group C,high school,free/reduced,none,62,55,55,pass,pass/fail
997,female,group C,high school,free/reduced,completed,59,71,65,pass,pass/fail
998,female,group D,some college,standard,completed,68,78,77,pass,pass/fail
999,female,group D,some college,free/reduced,none,77,86,86,pass,pass/fail

In [143]:
df.to_csv("C:\\Users\\MANi BABU\\Desktop\\data1.csv")